### ISSUE TITLE
Could not find Angular on page http://localhost:4200/

### ISSUE THREAD

**Issue by marvi14** [AdrianMarinica/bitbucket-pipelines-protractor#1]
I'm new to Bitbucket Pipelines, so I'm struggling a little bit trying to run my Protractor E2E tests of my Angular 2 application on the build. My bitbucket-pipelines.yml looks like this

```
image: adrianmarinica/bitbucket-pipelines-protractor

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - protractor protractor.conf.js
```
When all dependencies are installed and protractor starts ruuning, I get this error

https://i.stack.imgur.com/pjVek.png

How can I run my tests as I do successfully in my local machine?
